name: Deploying dev-app to firebase previews

on:
  workflow_run:
    workflows: [Build dev-app]
    types: [completed]

jobs:
  deploy-dev-app:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            const fs = require('fs');
            const artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });

            const matchArtifact = artifacts.data.artifacts
              .filter(artifact => artifact.name == "devapp")[0];

            const download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });

            fs.writeFileSync('${{github.workspace}}/devapp.zip', Buffer.from(download.data));

      - name: Extracting workflow artifact into Firebase public directory.
        run: |
          mkdir -p dist/dev-app-web-pkg
          unzip devapp.zip -d dist/dev-app-web-pkg

      - name: Extracting pull request from extracted workflow artifact.
        run: echo "::set-output name=number::$(cat ./dist/dev-app-web-pkg/pr_number)"
        id: pr_info

      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: deploy
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_PREVIEW_SERVICE_TOKEN }}"
          expires: 15d
          projectId: angular-components-test
          channelId: pr${{ steps.pr_info.outputs.number }}

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Deployed dev-app to: ${{ steps.deploy.outputs.details_url }}
          number: ${{ steps.pr_info.outputs.number }}
